name: remote_ssh_commands
description: 'Execute commands in a remote ssh server.'
author: 'Sithi5'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  SSH_USER:
    description: 'ssh user'
    required: true
  SSH_PRIVATE_KEY:
    description: 'ssh private key'
    required: true
  SSH_HOST:
    description: 'ssh host'
    required: true
  SSH_PORT:
    description: 'ssh port'
    default: 22
    required: false
  SSH_REMOTE_COMMANDS:
    description: 'command to execute in the remote server.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🔧 Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.SSH_PRIVATE_KEY }}" > ~/.ssh/server.key
        chmod 600 ~/.ssh/server.key
        cat >>~/.ssh/config <<END
        Host server
          HostName ${{ inputs.SSH_HOST }}
          User ${{ inputs.SSH_USER }}
          Port ${{ inputs.SSH_PORT }}
          IdentityFile ~/.ssh/server.key
          StrictHostKeyChecking no
        END
      shell: bash
    - name: 🔥 Execute ssh commands
      run: ssh server "${{ inputs.SSH_REMOTE_COMMANDS }}; exit"
      shell: bash
