name: remote ssh command
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to correct branch
        uses: actions/checkout@v2
      - name: Calling ssh_remote_commands action
        uses: ./
        with:
          SSH_USER: ${{ secrets.SSH_BASTION_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_BASTION_HOST }}
          SSH_REMOTE_COMMAND: ls -la
