name: remote ssh commands
on: [push]

jobs:
  build:
    name: Execute bash commands in remote ssh host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to correct branch
        uses: actions/checkout@v3
      - name: Calling ssh_remote_commands action
        uses: ./
        with:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_REMOTE_COMMANDS: pwd; echo 'Hello World ! ';pwd
